AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-hands-on

  Sample SAM Template for serverless-hands-on

Globals:
  Function:
    Timeout: 3

Resources:
  # API Gateway
  HandsOnApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: hands-on-api
      StageName: v1

  # Lambda functions
  UserCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/user/create/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        UserCreateApi:
          Type: Api
          Properties:
            Path: /user
            Method: post
            RestApiId:
              Ref: HandsOnApi
